gems:
  - directory: nl
    hooks:
      prebuild: bundle exec rake build
  - directory: ynl
    hooks:
      prebuild: bundle exec rake build
  - directory: nl-linux
    hooks:
      prebuild: bundle exec rake build
