module Ynl
  class Generator
    module Refinements
      WORD_DELIM = /[ _-]+/

      refine(String) do
        def as_const_name
          split(WORD_DELIM).map(&:upcase).join('_').tap {|s| s.prepend('X_') unless s.start_with?(/[A-Z]/i) }
        end

        def as_class_name
          split(WORD_DELIM).map(&:capitalize).join.tap {|s| s.prepend('X') unless s.start_with?(/[A-Z]/i) }
        end

        def as_variable_name
          split(WORD_DELIM).join('_').tap {|s| s.prepend('x_') unless s.start_with?(/[A-Z]/i) }
        end
        alias as_method_name as_variable_name

        def as_string_literal
          dump
        end

        def as_symbol_literal
          ":#{dump}"
        end
      end
    end
    # private_constant :Refinements

    using Refinements

    PRELUDE = -<<~RUBY
      # frozen_string_literal: true
      # rbs_inline: enabled
      # This code is generated by Ynl::Generator. DO NOT EDIT.
      require 'nl'
    RUBY

    OPERATION_FLAG_DOCS = {
      'admin-perm' => 'Requires CAP_NET_ADMIN in the initial user namespace.',
      'uns-admin-perm' => 'Requires CAP_NET_ADMIN in the user namespace owning the network namespace.',
    }.freeze
    private_constant :OPERATION_FLAG_DOCS

    def initialize(ynl, out)
      @ynl = ynl
      @out = out
      @indent = 0
    end

    def generate(superclass: nil, namespace: nil, default_resolver: nil)
      raw = @ynl.protocol == 'netlink-raw'
      @wire = raw ? '::Nl::Raw' : '::Nl::Genl'
      superclass ||= raw ? '::Nl::Raw::Family' : '::Nl::Genl::Family'
      build_selector_plan

      emit_comment(@ynl.doc)

      classname = @ynl.name.as_class_name
      emit_class([*namespace, classname].join('::'), superclass) do
        emit_const('NAME', @ynl.name.as_string_literal)

        emit_const('PROTONUM', @ynl.protonum) if raw
        emit_const('VERSION', @ynl.version) unless raw
        emit_default_resolver(default_resolver) if default_resolver && !raw

        emit_mcast_groups

        unless @ynl.consts.empty?
          emit_module('Constants') do
            @ynl.consts.each_value do |const|
              emit_comment(const.doc)
              emit_const(const.name.as_const_name, const_value_literal(const.value))
            end
          end
        end

        emit_value_definitions('Enums', @ynl.enums.values) { |_definition, entry| entry.value }
        emit_value_definitions('Flags', @ynl.flags.values + enums_used_as_flags) do |definition, entry|
          definition.is_a?(Models::Enum) ? 1 << entry.value : entry.value
        end

        deferred_struct_consts = []
        emit_module('Structs') do
          @ynl.structs.each do |name, struct|
            emit_comment(struct.doc)
            write(name.as_class_name, " = Struct.new(")
            indent do
              struct.members.each do |member|
                write(member.name.as_variable_name.as_symbol_literal, ', #: ', struct_member_rbs_type(member.type))
              end
            end
            write(')')
            emit_class(name.as_class_name) do
              emit_internal
              members = struct.members.map do |member|
                "#{member.name.as_variable_name}: #{to_struct_member_datatype(member.type)}"
              end
              members = "Ractor.make_shareable({#{members.join(', ')}})"
              if struct.members.any? { it.type.is_a?(Types::Binary) && it.type.struct }
                deferred_struct_consts << ["Structs::#{name.as_class_name}::MEMBERS", members]
              else
                emit_const('MEMBERS', members, rbs: 'Hash[::Symbol, ::Nl::_DataType]')
              end

              emit_comment('Decodes the struct.')
              emit_rbs_comment(
                'decoder: ::Nl::Decoder',
                'return: instance',
              )
              emit_yard_param('decoder', 'Nl::Decoder')
              emit_yard_return('self')
              write('def self.decode(decoder)')
              indent do
                write('self.new(*MEMBERS.map {|name, datatype| datatype.decode(decoder) })')
              end
              write('end')

              emit_comment('Encodes the struct.')
              emit_rbs_comment(
                'encoder: ::Nl::Encoder',
                'return: void',
              )
              emit_yard_param('encoder', 'Nl::Encoder')
              emit_yard_return('void')
              write('def encode(encoder)')
              indent do
                write('MEMBERS.each {|name, datatype| datatype.encode(encoder, self.public_send(name)) }')
              end
              write('end')
            end
          end
        end
        deferred_struct_consts.each do |name, members|
          emit_const(name, members, rbs: 'Hash[::Symbol, ::Nl::_DataType]')
        end

        deferred_sub_message_datatypes = []
        emit_module('AttributeSets') do
          deferred_consts = []
          @ynl.attribute_sets.each do |name, attr_set|
            emit_comment(attr_set.doc)
            emit_class(name.as_class_name, '::Nl::AttributeSet') do
              emit_comment("Abstract class")
              emit_class('Attribute', '::Nl::AttributeSet::Attribute') do
              end
              attr_set.attributes.each do |attr|
                emit_comment(attr.doc)
                emit_class(attr.name.as_class_name, 'Attribute') do
                  emit_const('TYPE', attr.value)
                  emit_const('NAME', attr.name.as_variable_name.as_symbol_literal)
                  emit_const('MULTI', 'true') if attr.multi?
                  emit_internal
                  emit_const('ORDER', @attribute_orders.fetch(attr_set).fetch(attr))
                  if slot = @local_selectors.fetch(attr_set).index(attr.name)
                    emit_internal
                    emit_const('SELECTOR_SLOT', slot)
                  end
                  if attr.type.is_a?(Types::SubMessage)
                    deferred_sub_message_datatypes << [
                      "AttributeSets::#{name.as_class_name}::#{attr.name.as_class_name}::DATATYPE",
                      to_datatype(attr.type, attr.checks, owner: attr_set),
                    ]
                  elsif attr.type.is_a?(Types::NestedAttributes) ||
                    attr.type.is_a?(Types::NestTypeValue) ||
                    (attr.type.is_a?(Types::IndexedArray) && attr.type.sub_type.is_a?(Types::NestedAttributes))
                    deferred_consts << ["#{name.as_class_name}::#{attr.name.as_class_name}::DATATYPE", to_datatype(attr.type, attr.checks, owner: attr_set)]
                  else
                    emit_const('DATATYPE', to_datatype(attr.type, attr.checks, owner: attr_set))
                  end
                end
              end

              selector_names = @local_selectors.fetch(attr_set)
              external_selector_names = @external_selectors.fetch(attr_set)
              unless selector_names.empty? && external_selector_names.empty?
                emit_internal
                emit_const(
                  'SELECTOR_NAMES',
                  "Ractor.make_shareable({local: [#{selector_names.map { it.as_variable_name.as_symbol_literal }.join(', ')}], external: [#{external_selector_names.map { it.as_variable_name.as_symbol_literal }.join(', ')}]})",
                )
              end

              emit_internal
              emit_const(
                'BY_NAME',
                "Ractor.make_shareable({#{attr_set.attributes.map { "#{it.name.as_variable_name.as_symbol_literal} => #{it.name.as_class_name}" }.join(', ') }})",
                rbs: 'Hash[::Symbol, Attribute]',
              )

              emit_internal
              emit_const(
                'BY_TYPE',
                "Ractor.make_shareable({#{attr_set.attributes.map { "#{it.value} => #{it.name.as_class_name}" }.join(', ') }})",
                rbs: 'Hash[::Integer, Attribute]',
              )

              attr_set.attributes.each do |attribute|
                next if attribute.type.is_a?(Types::Pad)

                emit_comment("Gets the value of `#{attribute.name}` attribute.")
                emit_rbs_comment('return: ' + attribute_rbs_type(attribute))
                emit_yard_return(attribute_yard_type(attribute))
                expression = if attribute.multi?
                  "self[#{attribute.name.as_variable_name.as_symbol_literal}].map(&:value)"
                else
                  "self[#{attribute.name.as_variable_name.as_symbol_literal}]&.value"
                end
                emit_getter(attribute.name.as_method_name, expression)
              end

              emit_singleton_class do
                emit_comment('Looks up Attribute class by name.')
                emit_rbs_comment(
                  'name: Symbol',
                  'return: Attribute',
                )
                emit_yard_param('name', 'Symbol')
                emit_yard_return('Attribute')
                emit_getter('by_name(name)', 'BY_NAME.fetch(name)')

                emit_comment('Looks up Attribute class by type value.')
                emit_rbs_comment(
                  'type: Integer',
                  'return: Attribute',
                )
                emit_yard_param('type', 'Integer')
                emit_yard_return('Attribute')
                emit_getter('by_type(type)', 'BY_TYPE.fetch(type)')
              end
            end
          end
          deferred_consts.each { emit_const(*it) }
        end


        emit_sub_messages
        deferred_sub_message_datatypes.each { emit_const(*it) }

        emit_module('Messages') do
          @ynl.operations.each do |name, oper|
            %w[do dump].each do |method|
              if request_reply = oper.public_send(method + 'it')
                %w[request reply].to_h { [it, request_reply.public_send(it)] }.compact.each do |type, msg|
                  emit_message_class(
                    method.as_class_name + oper.name.as_class_name + type.as_class_name,
                    msg,
                    fixed_header: oper.fixed_header,
                    attribute_set: oper.attribute_set,
                    doc: operation_doc(oper),
                  )
                end
              end
            end
          end
        end

        emit_module('Notifications') do
          notification_operations.each do |oper|
            message, fixed_header, attribute_set = notification_layout(oper)
            emit_message_class(
              oper.name.as_class_name,
              message,
              fixed_header:,
              attribute_set:,
              doc: notification_doc(oper),
            )
          end
        end

        emit_const(
          'NOTIFICATIONS',
          "Ractor.make_shareable({#{notification_operations.map { |oper| "#{oper.notification.message.value} => Notifications::#{oper.name.as_class_name}" }.join(', ') }})",
          rbs: 'Hash[::Integer, ::Class]',
        )

        # emit request methods
        @ynl.operations.each do |name, oper|
          %w[do dump].each do |method|
            if request_reply = oper.public_send(method + 'it')
              request = request_reply.request

              request_class = "Messages::#{method.as_class_name}#{oper.name.as_class_name}Request"
              reply_class = request_reply.reply ? "Messages::#{method.as_class_name}#{oper.name.as_class_name}Reply" : 'nil'

              header_params = oper.fixed_header&.members || []
              attribute_params = oper.attribute_set.attributes.filter { request.attributes.include?(it.name) }
              attribute_params.reject! {|a| header_params.any? {|h| h.name == a.name  } }  # The two params should have the same Ruby type anyway
              params = header_params + attribute_params
              params.reject! { it.type.is_a? Types::Pad }

              rbs_params = params.map { |it| "?#{it.name.as_variable_name}: #{parameter_rbs_type(it)}" }.join(', ')
              rbs_result = request_reply.reply ? reply_class : 'void'

              emit_comment(operation_doc(oper))
              if method == 'dump'
                emit_rbs_comment(
                  "(#{rbs_params}) -> Enumerable[#{rbs_result}]\n  | (#{rbs_params}) { (#{rbs_result}) -> void } -> void",
                )
                emit_yard_options(params)
                emit_yard_return("Enumerable<#{rbs_result}>, void")
                emit_yard_yieldparam('reply', rbs_result)
                write("def #{method.as_method_name}_#{oper.name.as_method_name}(**args, &block)")
                indent do
                  write("exchange_message(#{method.as_symbol_literal}, #{request_class}, #{reply_class}, args, &block)")
                end
              else
                emit_rbs_comment(
                  "(#{rbs_params}) -> #{rbs_result}",
                )
                emit_yard_options(params)
                emit_yard_return(rbs_result)
                write("def #{method.as_method_name}_#{oper.name.as_method_name}(**args)")
                indent do
                  write("exchange_message(#{method.as_symbol_literal}, #{request_class}, #{reply_class}, args)")
                end
              end
              write('end')
            end
          end
        end

        emit_class('AsyncOperations') do
          emit_internal
          write('def initialize(&exchange)')
          indent do
            write('@exchange = exchange')
          end
          write('end')

          @ynl.operations.each do |name, oper|
            %w[do dump].each do |method|
              next unless request_reply = oper.public_send(method + 'it')

              request_class = "Messages::#{method.as_class_name}#{oper.name.as_class_name}Request"
              reply_class = request_reply.reply ? "Messages::#{method.as_class_name}#{oper.name.as_class_name}Reply" : 'nil'
              header_params = oper.fixed_header&.members || []
              attribute_params = oper.attribute_set.attributes.filter { request_reply.request.attributes.include?(it.name) }
              attribute_params.reject! {|a| header_params.any? {|h| h.name == a.name } }
              params = (header_params + attribute_params).reject { it.type.is_a? Types::Pad }
              rbs_params = params.map { |it| "?#{it.name.as_variable_name}: #{parameter_rbs_type(it)}" }.join(', ')
              result = request_reply.reply ? reply_class : 'void'
              operation = method == 'dump' ? "::Nl::Async::Stream[#{result}]" : "::Nl::Async::Future[#{result}]"
              yard_operation = method == 'dump' ? "Nl::Async::Stream<#{result}>" : "Nl::Async::Future<#{result}>"

              emit_comment(operation_doc(oper))
              emit_rbs_comment("(#{rbs_params}) -> #{operation}")
              emit_yard_options(params)
              emit_yard_return(yard_operation)
              write("def #{method.as_method_name}_#{oper.name.as_method_name}(**args)")
              indent do
                write("@exchange.call(#{method.as_symbol_literal}, #{request_class}, #{reply_class}, args)")
              end
              write('end')
            end
          end
        end

        emit_comment('Returns the asynchronous operation facade for this family.')
        emit_rbs_comment('(?stream_capacity: ::Integer?) -> AsyncOperations')
        emit_yard_param('stream_capacity', '::Integer, nil')
        emit_yard_return('AsyncOperations')
        write('def async(stream_capacity: nil)')
        indent do
          write('return @async_operations ||= build_async_facade(AsyncOperations) if stream_capacity.nil?')
          write('build_async_facade(AsyncOperations, stream_capacity:)')
        end
        write('end')

        emit_subscription_methods unless @ynl.mcast_groups.empty?
      end

      classname
    end

    INDENT = -'  '
    NEWLINE = -?\n
    private_constant :INDENT, :NEWLINE

    private def write(*str)
      @out.write(INDENT * @indent, *str, NEWLINE)
    end

    private def indent
      @indent += 1
      yield
    ensure
      @indent -= 1
    end

    private def emit_module(name)
      write('module ', name)
      indent { yield }
      write('end')
    end

    private def emit_class(name, superclass = nil)
      if superclass
        write('class ', name, ' < ', superclass)
      else
        write('class ', name)
      end
      indent { yield }
      write('end')
    end

    private def emit_singleton_class
      write('class << self')
      indent { yield }
      write('end')
    end

    private def emit_const(name, value, rbs: nil)
      write(name, ' = ', value, *([' #: ', rbs] if rbs))
    end

    private def emit_value_definitions(namespace, definitions)
      return if definitions.empty?

      emit_module(namespace) do
        definitions.each do |definition|
          emit_comment(definition.doc)
          emit_module(definition.name.as_class_name) do
            definition.entries.each do |entry|
              emit_comment(entry.doc)
              emit_const(entry.name.as_class_name, yield(definition, entry))
            end
          end
        end
      end
    end

    private def enums_used_as_flags
      @ynl.attribute_sets.each_value.flat_map(&:attributes).filter_map do |attribute|
        next unless attribute.enum_as_flags && attribute.enum.is_a?(Models::Enum)

        attribute.enum
      end.uniq
    end

    private def emit_getter(name, expr)
      write('def ', name, '; ', expr, '; end')
    end

    private def emit_internal
      write('# @private')
    end

    private def emit_default_resolver(default_resolver)
      emit_rbs_comment(
        '(?resolver: ^(::Nl::Genl::Client, ::String) -> ::Nl::Genl::FamilyInfo, ?executor: executor?, ?notification_capacity: ::Integer?) -> (::Nl::Family::Session & instance)',
        '| [R] (?resolver: ^(::Nl::Genl::Client, ::String) -> ::Nl::Genl::FamilyInfo, ?executor: executor?, ?notification_capacity: ::Integer?) { (instance) -> R } -> R',
      )
      emit_yard_param('resolver', '#call')
      emit_yard_param('executor', 'Symbol, nil')
      emit_yard_param('notification_capacity', 'Integer, nil')
      emit_yard_return('::Nl::Family::Session, Object')
      write("def self.open(resolver: #{default_resolver}, executor: nil, notification_capacity: DEFAULT_NOTIFICATION_CAPACITY)")
      indent { write('super') }
      write('end')
    end

    private def emit_comment(comment)
      return unless comment
      comment.each_line(chomp: true) do |line|
        write('# ', line)
      end
    end

    private def operation_doc(operation)
      flag_docs = operation.flags.filter_map { OPERATION_FLAG_DOCS[it] }
      [operation.doc, *flag_docs].compact.join("\n\n")
    end

    private def notification_operations
      @notification_operations ||= @ynl.operations.values.select(&:notification)
    end

    private def notification_doc(operation)
      group = operation.notification.group
      [operation.doc, ("Multicast group: `#{group.name}`." if group)].compact.join("\n\n")
    end

    private def notification_layout(operation)
      notification = operation.notification
      if notification.kind == :event
        [notification.message, operation.fixed_header, operation.attribute_set]
      else
        source = notification.source
        mode = source.doit || source.dumpit
        reply = mode&.reply
        unless reply
          selected = source.doit ? 'do' : 'dump'
          raise ParseError,
            "Notification #{operation.name.inspect} references #{source.name.inspect}, which has no #{selected} reply"
        end
        message = Models::Message.new(
          value: notification.message.value,
          attributes: reply.attributes,
        )
        [message, source.fixed_header, source.attribute_set]
      end
    end

    private def emit_message_class(name, message, fixed_header:, attribute_set:, doc:)
      emit_comment(doc)
      emit_class(name, "#@wire::Message") do
        emit_const('TYPE', message.value)
        emit_const('FIXED_HEADER', fixed_header&.then { 'Structs::' + it.name.as_class_name } || 'nil')
        emit_const('ATTRIBUTE_SET', "AttributeSets::#{attribute_set.name.as_class_name}")
        attribute_params = attribute_set.attributes.map(&:name) & message.attributes
        emit_const('ATTRIBUTES', "Ractor.make_shareable(%i[#{attribute_params.map { it.as_variable_name }.join(' ')}])")
        fixed_header&.members&.each do |member|
          param = member.name
          datatype = member.type
          next if datatype.is_a? Types::Pad
          next if attribute_params.include?(param)
          emit_comment("Gets the value of `#{param}` field in the message's fixed header.")
          emit_rbs_comment('return: ' + struct_member_rbs_type(datatype))
          emit_yard_return(struct_member_yard_type(datatype))
          emit_getter(param.as_method_name, "fixed_header.#{param.as_method_name}")
        end
        attribute_params.each do |param|
          attribute = attribute_set.attributes.find { it.name == param }
          datatype = attribute.type
          next if datatype.is_a? Types::Pad
          extending = fixed_header&.members&.any? { it.name == param }

          if extending && attribute.multi?
            raise ParseError, "Multi-attribute #{param.inspect} conflicts with a fixed-header member"
          end

          if extending
            emit_comment("Gets the value of `#{param}` attribute or fixed header in the message.")
          else
            emit_comment("Gets the value of `#{param}` attribute in the message.")
          end
          emit_rbs_comment('return: ' + attribute_rbs_type(attribute))
          emit_yard_return(attribute_yard_type(attribute))
          if attribute.multi?
            emit_getter(param.as_method_name, "attributes[#{param.as_variable_name.as_symbol_literal}].map(&:value)")
            next
          end
          if extending
            emit_getter(param.as_method_name, "attributes[#{param.as_variable_name.as_symbol_literal}]&.value || fixed_header.#{param.as_method_name}")
          else
            emit_getter(param.as_method_name, "attributes[#{param.as_variable_name.as_symbol_literal}]&.value")
          end
        end
      end
    end

    private def emit_sub_messages
      return if @ynl.sub_messages.empty?

      emit_module('SubMessages') do
        @ynl.sub_messages.each_value do |sub_message|
          grouped = sub_message.formats.group_by { it.value.as_class_name }
          if collision = grouped.find { |_name, formats| formats.length > 1 }
            ruby_name, formats = collision
            raise ParseError,
              "Sub-message formats #{formats.map(&:value).map(&:inspect).join(' and ')} normalize to #{ruby_name.inspect}"
          end
          emit_module(sub_message.name.as_class_name) do
            sub_message.formats.each do |format|
              emit_sub_message_class(format.value.as_class_name, format)
            end
          end
        end
      end
    end

    private def emit_sub_message_class(name, format)
      emit_class(name, '::Nl::SubMessage') do
        emit_const('FIXED_HEADER', format.fixed_header&.then { 'Structs::' + it.name.as_class_name } || 'nil')
        emit_const('ATTRIBUTE_SET', format.attribute_set&.then { 'AttributeSets::' + it.name.as_class_name } || 'nil')

        format.fixed_header&.members&.each do |member|
          next if member.type.is_a?(Types::Pad)
          extending = format.attribute_set&.attributes&.any? { it.name == member.name }
          next if extending
          emit_comment("Gets the value of `#{member.name}` field in the sub-message's fixed header.")
          emit_rbs_comment('return: ' + struct_member_rbs_type(member.type))
          emit_yard_return(struct_member_yard_type(member.type))
          emit_getter(member.name.as_method_name, "fixed_header.#{member.name.as_method_name}")
        end

        format.attribute_set&.attributes&.each do |attribute|
          next if attribute.type.is_a?(Types::Pad)
          extending = format.fixed_header&.members&.any? { it.name == attribute.name }
          emit_comment("Gets the value of `#{attribute.name}` in the sub-message.")
          emit_rbs_comment('return: ' + attribute_rbs_type(attribute))
          emit_yard_return(attribute_yard_type(attribute))
          expression = if attribute.multi?
            "attributes[#{attribute.name.as_variable_name.as_symbol_literal}].map(&:value)"
          elsif extending
            "attributes[#{attribute.name.as_variable_name.as_symbol_literal}]&.value || fixed_header.#{attribute.name.as_method_name}"
          else
            "attributes[#{attribute.name.as_variable_name.as_symbol_literal}]&.value"
          end
          emit_getter(attribute.name.as_method_name, expression)
        end
      end
    end

    private def parameter_rbs_type(param)
      if param.is_a?(Models::AttributeSet::Attribute)
        type = input_rbs_type(param.type)
        param.multi? ? "::Array[#{type}]" : type
      else
        struct_member_rbs_type(param.type)
      end
    end

    private def parameter_yard_type(param)
      if param.is_a?(Models::AttributeSet::Attribute)
        type = input_yard_type(param.type)
        param.multi? ? "Array<#{type}>" : type
      else
        struct_member_yard_type(param.type)
      end
    end

    private def struct_member_rbs_type(type)
      if type.is_a?(Types::Binary) && type.struct
        'Structs::' + type.struct.name.as_class_name
      else
        type.rbs_type
      end
    end

    private def struct_member_yard_type(type)
      if type.is_a?(Types::Binary) && type.struct
        'Structs::' + type.struct.name.as_class_name
      else
        yard_type(type)
      end
    end

    private def input_rbs_type(type)
      case type
      when Types::NestedAttributes
        "(#{type.rbs_type} | ::Hash[::Symbol, untyped])"
      when Types::Binary
        type.struct ? "(#{type.rbs_type} | ::Hash[::Symbol, untyped])" : type.rbs_type
      when Types::PackedArray
        "::Array[#{input_rbs_type(type.sub_type)}]"
      when Types::NestTypeValue
        value_type = "(AttributeSets::#{type.attribute_set.name.as_class_name} | ::Hash[::Symbol, untyped])"
        type.type_values.length.times { value_type = "::Hash[::Integer, #{value_type}]" }
        value_type
      when Types::IndexedArray
        "::Array[#{input_rbs_type(type.sub_type)}]"
      when Types::SubMessage
        "(#{sub_message_rbs_type(type)} | ::Hash[::Symbol, untyped])"
      else
        type.rbs_type
      end
    end

    private def input_yard_type(type)
      case type
      when Types::NestedAttributes
        "#{yard_type(type)}, Hash<Symbol, Object>"
      when Types::Binary
        type.struct ? "#{yard_type(type)}, Hash<Symbol, Object>" : yard_type(type)
      when Types::PackedArray, Types::IndexedArray
        "Array<#{input_yard_type(type.sub_type)}>"
      when Types::NestTypeValue
        value_type = "AttributeSets::#{type.attribute_set.name.as_class_name}, Hash<Symbol, Object>"
        type.type_values.length.times { value_type = "Hash<Integer, #{value_type}>" }
        value_type
      when Types::SubMessage
        "#{sub_message_yard_type(type)}, Hash<Symbol, Object>"
      else
        yard_type(type)
      end
    end

    private def attribute_rbs_type(attribute)
      type = if attribute.type.is_a?(Types::SubMessage)
        sub_message_rbs_type(attribute.type)
      else
        attribute.type.rbs_type
      end
      attribute.multi? ? "::Array[#{type}]" : type
    end

    private def attribute_yard_type(attribute)
      type = if attribute.type.is_a?(Types::SubMessage)
        sub_message_yard_type(attribute.type)
      else
        yard_type(attribute.type)
      end
      attribute.multi? ? "Array<#{type}>" : type
    end

    private def sub_message_rbs_type(type)
      formats = type.sub_message.formats.map do |format|
        "SubMessages::#{type.sub_message.name.as_class_name}::#{format.value.as_class_name}"
      end
      (formats << '::Nl::RawSubMessage').join(' | ')
    end

    private def sub_message_yard_type(type)
      formats = type.sub_message.formats.map do |format|
        "SubMessages::#{type.sub_message.name.as_class_name}::#{format.value.as_class_name}"
      end
      (formats << 'Nl::RawSubMessage').join(', ')
    end

    private def yard_type(type)
      case type
      when Types::Scalar, Types::Flag
        'Integer'
      when Types::String
        'String'
      when Types::Binary
        type.struct ? 'Structs::' + type.struct.name.as_class_name : 'String'
      when Types::PackedArray, Types::IndexedArray
        "Array<#{yard_type(type.sub_type)}>"
      when Types::NestedAttributes
        'AttributeSets::' + type.attribute_set.name.as_class_name
      when Types::NestTypeValue
        value_type = 'AttributeSets::' + type.attribute_set.name.as_class_name
        type.type_values.length.times { value_type = "Hash<Integer, #{value_type}>" }
        value_type
      when Types::SubMessage
        'Nl::SubMessage'
      when Types::Pad
        'nil'
      when Types::Bitfield32
        'Nl::Bitfield32'
      else
        raise "Unknown YARD type: #{type.class}"
      end
    end

    private def emit_mcast_groups
      groups = @ynl.mcast_groups.values
      grouped = groups.group_by { it.name.as_variable_name }
      if collision = grouped.find { |_name, matches| matches.length > 1 }
        ruby_name, matches = collision
        raise ParseError,
          "Multicast groups #{matches.map(&:name).map(&:inspect).join(' and ')} normalize to #{ruby_name.to_sym.inspect}"
      end

      entries = groups.map do |group|
        key = group.name.as_variable_name.as_symbol_literal
        value = "::Nl::McastGroup.new(#{group.name.as_string_literal}, #{mcast_group_value_literal(group.value)})"
        "#{key} => #{value}"
      end
      emit_const(
        'MCAST_GROUPS',
        "Ractor.make_shareable({#{entries.join(', ')}})",
        rbs: 'Hash[::Symbol, ::Nl::McastGroup]',
      )
    end

    private def emit_subscription_methods
      groups = @ynl.mcast_groups.values
        .map { ":#{it.name.as_variable_name}" }
      emit_rbs_comment("(*(#{groups.join(' | ')}) groups) -> self")
      emit_yard_param('groups', "Array<#{groups.join(', ')}>")
      emit_yard_return('self')
      write('def subscribe(*groups) = super')
      emit_rbs_comment("(*(#{groups.join(' | ')}) groups) -> self")
      emit_yard_param('groups', "Array<#{groups.join(', ')}>")
      emit_yard_return('self')
      write('def unsubscribe(*groups) = super')
    end

    private def emit_rbs_comment(*args)
      args.each do |arg|
        emit_comment('@rbs ' + arg)
      end
    end

    private def emit_yard_options(params)
      emit_yard_param('args', 'Hash')
      params.each do |param|
        emit_yard_option('args', param.name.as_variable_name, parameter_yard_type(param))
      end
    end

    private def emit_yard_option(parameter, name, type)
      emit_comment("@option #{parameter} [#{type}] #{name}")
    end

    private def emit_yard_param(name, type)
      emit_comment("@param [#{type}] #{name}")
    end

    private def emit_yard_return(type)
      emit_comment("@return [#{type}]")
    end

    private def emit_yard_yieldparam(name, type)
      emit_comment("@yieldparam [#{type}] #{name}")
    end

    private def build_selector_plan
      sets = @ynl.attribute_sets.values
      @local_selectors = sets.to_h { [it, []] }
      @external_selectors = sets.to_h { [it, []] }

      @ynl.sub_messages.each_value do |sub_message|
        duplicate = sub_message.formats.group_by(&:value).find { |_value, formats| formats.length > 1 }
        if duplicate
          raise ParseError,
            "Duplicate format value #{duplicate.first.inspect} in sub-message #{sub_message.name.inspect}"
        end
      end

      changed = true
      while changed
        changed = false
        sets.each do |set|
          set.attributes.each do |attribute|
            if attribute.type.is_a?(Types::SubMessage)
              changed |= require_selector(set, attribute.type.selector)
            end

            child_attribute_sets(attribute.type).each do |child|
              @external_selectors.fetch(child).each do |selector|
                changed |= require_selector(set, selector)
              end
            end
          end
        end
      end

      build_attribute_orders
      roots = @ynl.operations.values.filter_map(&:attribute_set).uniq
      roots.each do |root|
        required = @external_selectors.fetch(root)
        next if required.empty?
        raise ParseError,
          "Root attribute set #{root.name.inspect} requires external selectors: #{required.join(', ')}"
      end
      build_selector_sources(roots)
      validate_selector_values
    end

    private def require_selector(set, selector)
      local = attribute_by_name(set, selector)
      if local&.multi?
        raise ParseError,
          "Multi-attribute #{selector.inspect} cannot be a selector in attribute set #{set.name.inspect}"
      end
      target = local ? @local_selectors : @external_selectors
      selectors = target.fetch(set)
      return false if selectors.include?(selector)
      selectors << selector
      true
    end

    private def build_attribute_orders
      @attribute_orders = {}
      @ynl.attribute_sets.each_value do |set|
        dependencies = set.attributes.to_h { |attribute| [attribute, []] }
        set.attributes.each do |attribute|
          selectors = []
          selectors << attribute.type.selector if attribute.type.is_a?(Types::SubMessage)
          child_attribute_sets(attribute.type).each do |child|
            selectors.concat(@external_selectors.fetch(child))
          end

          selectors.uniq.each do |selector|
            selector_attribute = attribute_by_name(set, selector)
            dependencies.fetch(attribute) << selector_attribute if selector_attribute
          end
        end

        ordered = []
        remaining = set.attributes.dup
        until remaining.empty?
          index = remaining.index do |attribute|
            dependencies.fetch(attribute).all? { ordered.include?(it) }
          end
          unless index
            raise ParseError,
              "Selector dependency cycle in attribute set #{set.name.inspect}: #{remaining.map(&:name).join(', ')}"
          end
          ordered << remaining.delete_at(index)
        end
        @attribute_orders[set] = ordered.each_with_index.to_h
      end
    end

    private def build_selector_sources(roots)
      @selector_sources = @ynl.attribute_sets.values.to_h { [it, Hash.new { |h, k| h[k] = [] }] }
      reached = roots.to_h { [it, true] }

      changed = true
      while changed
        changed = false
        reached.keys.each do |set|
          set.attributes.each do |attribute|
            child_attribute_sets(attribute.type).each do |child|
              unless reached[child]
                reached[child] = true
                changed = true
              end
              @external_selectors.fetch(child).each do |selector|
                sources = if source = attribute_by_name(set, selector)
                  [source]
                else
                  @selector_sources.fetch(set)[selector]
                end
                target = @selector_sources.fetch(child)[selector]
                sources.each do |candidate|
                  unless target.include?(candidate)
                    target << candidate
                    changed = true
                  end
                end
              end
            end
          end
        end
      end
    end

    private def validate_selector_values
      @ynl.attribute_sets.each_value do |set|
        set.attributes.each do |attribute|
          next unless attribute.type.is_a?(Types::SubMessage)
          keys = attribute.type.sub_message.formats.map do |format|
            selector_value_literal(set, attribute.type.selector, format.value)
          end
          duplicate = keys.group_by(&:itself).find { |_key, matches| matches.length > 1 }
          if duplicate
            raise ParseError,
              "Sub-message #{attribute.type.sub_message.name.inspect} has duplicate compiled selector value #{duplicate.first}"
          end
        end
      end
    end

    private def child_attribute_sets(type)
      case type
      when Types::NestedAttributes, Types::NestTypeValue
        [type.attribute_set]
      when Types::IndexedArray
        child_attribute_sets(type.sub_type)
      when Types::SubMessage
        type.sub_message.formats.filter_map(&:attribute_set)
      else
        []
      end
    end

    private def attribute_by_name(set, name)
      set.attributes.find { it.name == name }
    end

    private def selector_source_literal(set, selector)
      if (index = @local_selectors.fetch(set).index(selector))
        "::Nl::Selector::Local.new(#{index})"
      elsif (index = @external_selectors.fetch(set).index(selector))
        "::Nl::Selector::External.new(#{index})"
      else
        raise ParseError, "Unresolved selector #{selector.inspect} in attribute set #{set.name.inspect}"
      end
    end

    private def selector_bindings_literal(parent, child)
      return '[]' unless child
      bindings = @external_selectors.fetch(child).map do |selector|
        selector_source_literal(parent, selector)
      end
      "Ractor.make_shareable([#{bindings.join(', ')}])"
    end

    private def selector_value_literal(set, selector, format_value)
      sources = if source = attribute_by_name(set, selector)
        [source]
      else
        @selector_sources.fetch(set)[selector]
      end
      if sources.empty?
        raise ParseError,
          "Cannot determine the type of external selector #{selector.inspect} in attribute set #{set.name.inspect}"
      end

      values = sources.map do |source|
        case source.type
        when Types::String
          format_value.as_string_literal
        when Types::Scalar
          unless source.enum.is_a?(Models::Enum)
            raise ParseError,
              "Integer selector #{source.name.inspect} must reference an enum"
          end
          entry = source.enum.entries.find { it.name == format_value }
          unless entry
            raise ParseError,
              "Selector enum #{source.enum.name.inspect} has no entry #{format_value.inspect}"
          end
          entry.value.to_s
        else
          raise ParseError,
            "Selector #{source.name.inspect} must be a string or an enum-backed integer"
        end
      end.uniq
      if values.length != 1
        raise ParseError,
          "Selector #{selector.inspect} has incompatible definitions for format #{format_value.inspect}"
      end
      values.first
    end

    private def to_datatype(type, checks, owner: nil)
      case type
      when Types::Pad
        "::Nl::DataTypes::Pad.new(#{type.length})"
      when Types::Flag
        "::Nl::DataTypes::Flag.new"
      when Types::Bitfield32
        "::Nl::DataTypes::Bitfield32.new"
      when Types::Scalar
        byte_order = "::Nl::Endian::#{type.byte_order.name.as_class_name}"
        if ['sint', 'uint'].include?(type.type)
          "::Nl::DataTypes::VariableInteger.new(#{byte_order}, signed: #{type.type == 'sint'}, check: #{to_checks(checks)})"
        else
          "::Nl::DataTypes::Scalar.new(#{byte_order}::#{type.type.as_const_name}, check: #{to_checks(checks)})"
        end
      when Types::String
        "::Nl::DataTypes::String.new(check: #{to_checks(checks)})"
      when Types::Binary
        if type.struct
          "::Nl::DataTypes::Struct.new(Structs::#{type.struct.name.as_class_name}, check: #{to_checks(checks)}, consume_remaining: true)"
        else
          "::Nl::DataTypes::Binary.new(check: #{to_checks(checks)})"
        end
      when Types::PackedArray
        "::Nl::DataTypes::PackedArray.new(#{to_datatype(type.sub_type, nil)}, check: #{to_checks(checks)})"
      when Types::NestedAttributes
        bindings = selector_bindings_literal(owner, type.attribute_set)
        "::Nl::DataTypes::NestedAttributes.new(AttributeSets::#{type.attribute_set.name.as_class_name}, selector_bindings: #{bindings})"
      when Types::NestTypeValue
        bindings = selector_bindings_literal(owner, type.attribute_set)
        "::Nl::DataTypes::NestTypeValue.new(AttributeSets::#{type.attribute_set.name.as_class_name}, #{type.type_values.length}, selector_bindings: #{bindings})"
      when Types::IndexedArray
        "::Nl::DataTypes::IndexedArray.new(#{to_datatype(type.sub_type, nil, owner:)})"
      when Types::SubMessage
        selector = selector_source_literal(owner, type.selector)
        formats = type.sub_message.formats.map do |format|
          key = selector_value_literal(owner, type.selector, format.value)
          klass = "SubMessages::#{type.sub_message.name.as_class_name}::#{format.value.as_class_name}"
          bindings = selector_bindings_literal(owner, format.attribute_set)
          nested = !format.attribute_set.nil?
          "#{key} => ::Nl::DataTypes::SubMessage::Format.new(#{klass}, #{bindings}, #{nested})"
        end
        "::Nl::DataTypes::SubMessage.new(#{selector}, {#{formats.join(', ')}})"
      else
        raise "Unknown type: #{type.class}"
      end
    end

    private def to_struct_member_datatype(type)
      if type.is_a?(Types::Binary) && type.struct
        "::Nl::DataTypes::Struct.new(Structs::#{type.struct.name.as_class_name}, check: nil)"
      elsif type.is_a?(Types::Binary)
        "::Nl::DataTypes::Binary.new(length: #{type.length}, check: nil)"
      else
        to_datatype(type, nil)
      end
    end

    private def to_checks(checks)
      return 'nil' if !checks || checks.empty?
      %Q{-> { #{checks.map { to_check(it) }.join('; ')} }}
    end

    private def to_check(check)
      value = case check.value
      when Models::Const
        "Constants::#{check.value.name.as_const_name}"
      else
        integer_literal(check.value)
      end

      comparison, description = case check.operation
      when 'max'
        ["it <= #{value}", "greater than maximum #{check_message_value(check, value)}"]
      when 'min'
        ["it >= #{value}", "less than minimum #{check_message_value(check, value)}"]
      when 'min-len'
        ["it.bytesize >= #{value}", "shorter than minimum length #{check_message_value(check, value)}"]
      when 'max-len'
        ["it.bytesize <= #{value}", "longer than maximum length #{check_message_value(check, value)}"]
      when 'exact-len'
        ["it.bytesize == #{value}", "not equal to length #{check_message_value(check, value)}"]
      else
        raise "Unknown check: #{check.operation}"
      end

      %Q{raise ArgumentError, "Value \#{it.inspect} is #{description}" unless #{comparison}}
    end

    private def check_message_value(check, value)
      check.value.is_a?(Models::Const) ? "\#{#{value}}" : value
    end

    private def const_value_literal(value)
      case value
      when Integer
        value.to_s
      when String
        value.as_string_literal
      else
        raise ParseError, "YNL constant value must be a string or an integer, got #{value.class}"
      end
    end

    private def integer_literal(value)
      unless value.is_a?(Integer)
        raise ParseError, "YNL check value must be an integer, got #{value.class}"
      end

      value.to_s
    end

    private def mcast_group_value_literal(value)
      case value
      when Integer
        value.to_s
      when nil
        'nil'
      else
        raise ParseError, "YNL multicast group value must be an integer, got #{value.class}"
      end
    end
  end
end
