module Ynl
  class Generator
    module Refinements
      WORD_DELIM = /[ _-]+/

      refine(String) do
        def as_const_name
          split(WORD_DELIM).map(&:upcase).join('_').tap {|s| s.prepend('X_') unless s.start_with?(/[A-Z]/i) }
        end

        def as_class_name
          split(WORD_DELIM).map(&:capitalize).join.tap {|s| s.prepend('X') unless s.start_with?(/[A-Z]/i) }
        end

        def as_variable_name
          split(WORD_DELIM).join('_').tap {|s| s.prepend('x_') unless s.start_with?(/[A-Z]/i) }
        end
        alias as_method_name as_variable_name

        def as_string_literal
          dump
        end

        def as_symbol_literal
          ":#{dump}"
        end
      end
    end
    # private_constant :Refinements

    using Refinements

    PRELUDE = -<<~RUBY
      # frozen_string_literal: true
      # rbs_inline: enabled
      # This code is generated by Ynl::Generator. DO NOT EDIT.
      require 'nl'
    RUBY

    OPERATION_FLAG_DOCS = {
      'admin-perm' => 'Requires CAP_NET_ADMIN in the initial user namespace.',
      'uns-admin-perm' => 'Requires CAP_NET_ADMIN in the user namespace owning the network namespace.',
    }.freeze
    private_constant :OPERATION_FLAG_DOCS

    def initialize(ynl, out)
      @ynl = ynl
      @out = out
      @indent = 0
    end

    def generate(superclass: '::Nl::Family', namespace: nil)
      @protocol = '::Nl::Protocols::' + (@ynl.protocol == 'netlink-raw' ? 'Raw' : 'Genl')

      emit_comment(@ynl.doc)

      classname = @ynl.name.as_class_name
      emit_class([*namespace, classname].join('::'), superclass) do
        emit_const('NAME', @ynl.name.as_string_literal)

        if @ynl.protocol == 'netlink-raw'
          emit_const('PROTOCOL', "Ractor.make_shareable(::Nl::Protocols::Raw.new(#{@ynl.name.as_string_literal}, #{@ynl.protonum}))")
        else
          emit_const('PROTOCOL', "Ractor.make_shareable(::Nl::Protocols::Genl.new(#{@ynl.name.as_string_literal}))")
        end

        emit_module('Structs') do
          @ynl.structs.each do |name, struct|
            emit_comment(struct.doc)
            write(name.as_class_name, " = Struct.new(")
            indent do
              struct.members.each do |member|
                write(member.name.as_variable_name.as_symbol_literal, ', #: ', member.type.rbs_type)
              end
            end
            write(')')
            emit_class(name.as_class_name) do
              emit_nodoc
              emit_const(
                'MEMBERS',
                "Ractor.make_shareable({#{struct.members.map { "#{it.name.as_variable_name}: #{to_datatype(it.type, nil)}" }.join(', ') }})",
                rbs: 'Hash[::Symbol, ::Nl::_DataType]',
              )

              emit_comment('Decodes the struct.')
              emit_rbs_comment(
                'decoder: ::Nl::Decoder',
                'return: instance',
              )
              write('def self.decode(decoder)')
              indent do
                write('self.new(*MEMBERS.map {|name, datatype| datatype.decode(decoder) })')
              end
              write('end')

              emit_comment('Encodes the struct.')
              emit_rbs_comment(
                'encoder: ::Nl::Encoder',
                'return: void',
              )
              write('def encode(encoder)')
              indent do
                write('MEMBERS.each {|name, datatype| datatype.encode(encoder, self.public_send(name)) }')
              end
              write('end')
            end
          end
        end

        emit_module('AttributeSets') do
          deferred_consts = []
          @ynl.attribute_sets.each do |name, attr_set|
            emit_comment(attr_set.doc)
            emit_class(name.as_class_name, @protocol + '::AttributeSet') do
              emit_comment("Abstract class")
              emit_class('Attribute', @protocol + '::AttributeSet::Attribute') do
              end
              attr_set.attributes.each do |attr|
                emit_comment(attr.doc)
                emit_class(attr.name.as_class_name, 'Attribute') do
                  emit_const('TYPE', attr.value)
                  emit_const('NAME', attr.name.as_variable_name.as_symbol_literal)
                  if attr.type.is_a?(Types::NestedAttributes) ||
                    attr.type.is_a?(Types::NestTypeValue) ||
                    (attr.type.is_a?(Types::IndexedArray) && attr.type.sub_type.is_a?(Types::NestedAttributes))
                    deferred_consts << ["#{name.as_class_name}::#{attr.name.as_class_name}::DATATYPE", to_datatype(attr.type, attr.checks)]
                  else
                    emit_const('DATATYPE', to_datatype(attr.type, attr.checks))
                  end
                end
              end

              emit_nodoc
              emit_const(
                'BY_NAME',
                "Ractor.make_shareable({#{attr_set.attributes.map { "#{it.name.as_variable_name.as_symbol_literal} => #{it.name.as_class_name}" }.join(', ') }})",
                rbs: 'Hash[::Symbol, Attribute]',
              )

              emit_nodoc
              emit_const(
                'BY_TYPE',
                "Ractor.make_shareable({#{attr_set.attributes.map { "#{it.value} => #{it.name.as_class_name}" }.join(', ') }})",
                rbs: 'Hash[::Integer, Attribute]',
              )

              emit_singleton_class do
                emit_comment('Looks up Attribute class by name.')
                emit_rbs_comment(
                  'name: Symbol',
                  'return: Attribute',
                )
                emit_getter('by_name(name)', 'BY_NAME.fetch(name)')

                emit_comment('Looks up Attribute class by type value.')
                emit_rbs_comment(
                  'type: Integer',
                  'return: Attribute',
                )
                emit_getter('by_type(type)', 'BY_TYPE.fetch(type)')
              end
            end
          end
          deferred_consts.each { emit_const(*it) }
        end

        emit_module('Messages') do
          @ynl.operations.each do |name, oper|
            %w[do dump].each do |method|
              if request_reply = oper.public_send(method + 'it')
                %w[request reply].to_h { [it, request_reply.public_send(it)] }.compact.each do |type, msg|
                  emit_comment(operation_doc(oper))
                  emit_class(method.as_class_name + oper.name.as_class_name + type.as_class_name, "#{@protocol}::Message") do
                    emit_const('TYPE', msg.value)
                    emit_const('FIXED_HEADER', oper.fixed_header&.then { 'Structs::' + it.name.as_class_name } || 'nil')
                    emit_const('ATTRIBUTE_SET', "AttributeSets::#{oper.attribute_set.name.as_class_name}")
                    params = msg.attributes
                    attribute_params = oper.attribute_set.attributes.map(&:name) & params
                    emit_const('ATTRIBUTES', "Ractor.make_shareable(%i[#{attribute_params.map { it.as_variable_name }.join(' ')}])")
                    oper.fixed_header.members.each do |member|
                      param = member.name
                      datatype = member.type
                      next if datatype.is_a? Types::Pad
                      next if attribute_params.include?(param)
                      emit_comment("Gets the value of `#{param}` field in the message's fixed header.")
                      emit_rbs_comment(
                        'return: ' + datatype.rbs_type,
                      )
                      emit_getter(param.as_method_name, "fixed_header.#{param.as_method_name}")
                    end if oper.fixed_header
                    attribute_params.each do |param|
                      datatype = oper.attribute_set.attributes.find { it.name == param }.type
                      next if datatype.is_a? Types::Pad
                      extending = oper.fixed_header&.members&.any? { it.name == param }

                      if extending
                        emit_comment("Gets the value of `#{param}` attribute or fixed header in the message.")
                      else
                        emit_comment("Gets the value of `#{param}` attribute in the message.")
                      end
                      emit_rbs_comment(
                        'return: ' + datatype.rbs_type,
                      )
                      if extending
                        # If the fixed header and the attribute set have the same-name parameter, the value from the attribute should have
                        # the precedence over that from the header.
                        emit_getter(param.as_method_name, "attributes[#{param.as_variable_name.as_symbol_literal}]&.value || fixed_header.#{param.as_method_name}")
                      else
                        emit_getter(param.as_method_name, "attributes[#{param.as_variable_name.as_symbol_literal}]&.value")
                      end
                    end
                  end
                end
              end
            end
          end
        end

        # emit request methods
        @ynl.operations.each do |name, oper|
          %w[do dump].each do |method|
            if request_reply = oper.public_send(method + 'it')
              request = request_reply.request

              request_class = "Messages::#{method.as_class_name}#{oper.name.as_class_name}Request"
              reply_class = request_reply.reply ? "Messages::#{method.as_class_name}#{oper.name.as_class_name}Reply" : 'nil'

              header_params = oper.fixed_header&.members || []
              attribute_params = oper.attribute_set.attributes.filter { request.attributes.include?(it.name) }
              attribute_params.reject! {|a| header_params.any? {|h| h.name == a.name  } }  # The two params should have the same Ruby type anyway
              params = header_params + attribute_params
              params.reject! { it.type.is_a? Types::Pad }

              rbs_params = params.map { |it| "?#{it.name.as_variable_name}: #{it.type.rbs_type}" }.join(', ')
              rbs_result = request_reply.reply ? reply_class : 'void'

              emit_comment(operation_doc(oper))
              if method == 'dump'
                emit_rbs_comment(
                  "(#{rbs_params}) -> Enumerable[#{rbs_result}]\n  | (#{rbs_params}) { (#{rbs_result}) -> void } -> void",
                )
                write("def #{method.as_method_name}_#{oper.name.as_method_name}(**args, &block)")
                indent do
                  write("exchange_message(#{method.as_symbol_literal}, #{request_class}, #{reply_class}, args, &block)")
                end
              else
                emit_rbs_comment(
                  "(#{rbs_params}) -> #{rbs_result}",
                )
                write("def #{method.as_method_name}_#{oper.name.as_method_name}(**args)")
                indent do
                  write("exchange_message(#{method.as_symbol_literal}, #{request_class}, #{reply_class}, args)")
                end
              end
              write('end')
            end
          end
        end

        emit_class('AsyncOperations') do
          emit_nodoc
          write('def initialize(&exchange)')
          indent do
            write('@exchange = exchange')
          end
          write('end')

          @ynl.operations.each do |name, oper|
            %w[do dump].each do |method|
              next unless request_reply = oper.public_send(method + 'it')

              request_class = "Messages::#{method.as_class_name}#{oper.name.as_class_name}Request"
              reply_class = request_reply.reply ? "Messages::#{method.as_class_name}#{oper.name.as_class_name}Reply" : 'nil'
              header_params = oper.fixed_header&.members || []
              attribute_params = oper.attribute_set.attributes.filter { request_reply.request.attributes.include?(it.name) }
              attribute_params.reject! {|a| header_params.any? {|h| h.name == a.name } }
              params = (header_params + attribute_params).reject { it.type.is_a? Types::Pad }
              rbs_params = params.map { |it| "?#{it.name.as_variable_name}: #{it.type.rbs_type}" }.join(', ')
              result = request_reply.reply ? reply_class : 'void'
              operation = method == 'dump' ? "::Nl::Async::Stream[#{result}]" : "::Nl::Async::Future[#{result}]"

              emit_comment(operation_doc(oper))
              emit_rbs_comment("(#{rbs_params}) -> #{operation}")
              write("def #{method.as_method_name}_#{oper.name.as_method_name}(**args)")
              indent do
                write("@exchange.call(#{method.as_symbol_literal}, #{request_class}, #{reply_class}, args)")
              end
              write('end')
            end
          end
        end

        emit_comment('Returns the asynchronous operation facade for this family.')
        emit_rbs_comment('(?stream_capacity: ::Integer?) -> AsyncOperations')
        write('def async(stream_capacity: nil)')
        indent do
          write('return @async_operations ||= build_async_facade(AsyncOperations) if stream_capacity.nil?')
          write('build_async_facade(AsyncOperations, stream_capacity:)')
        end
        write('end')
      end

      classname
    end

    INDENT = -'  '
    NEWLINE = -?\n
    private_constant :INDENT, :NEWLINE

    private def write(*str)
      @out.write(INDENT * @indent, *str, NEWLINE)
    end

    private def indent
      @indent += 1
      yield
    ensure
      @indent -= 1
    end

    private def emit_module(name)
      write('module ', name)
      indent { yield }
      write('end')
    end

    private def emit_class(name, superclass = nil)
      if superclass
        write('class ', name, ' < ', superclass)
      else
        write('class ', name)
      end
      indent { yield }
      write('end')
    end

    private def emit_singleton_class
      write('class << self')
      indent { yield }
      write('end')
    end

    private def emit_const(name, value, rbs: nil)
      write(name, ' = ', value, *([' #: ', rbs] if rbs))
    end

    private def emit_getter(name, expr)
      write('def ', name, '; ', expr, '; end')
    end

    private def emit_nodoc
      write('# :nodoc:')
    end

    private def emit_comment(comment)
      return unless comment
      comment.each_line(chomp: true) do |line|
        write('# ', line)
      end
    end

    private def operation_doc(operation)
      flag_docs = operation.flags.filter_map { OPERATION_FLAG_DOCS[it] }
      [operation.doc, *flag_docs].compact.join("\n\n")
    end

    private def emit_rbs_comment(*args)
      write('#--')
      args.each do |arg|
        emit_comment('@rbs ' + arg)
      end
    end

    private def to_datatype(type, checks)
      case type
      when Types::Pad
        "#{@protocol}::DataTypes::Pad.new(#{type.length})"
      when Types::Flag
        "#{@protocol}::DataTypes::Flag.new"
      when Types::Bitfield32
        "#{@protocol}::DataTypes::Bitfield32.new"
      when Types::Scalar
        "#{@protocol}::DataTypes::Scalar.new(::Nl::Endian::#{type.byte_order.name.as_class_name}::#{type.type.as_const_name}, check: #{to_checks(checks)})"
      when Types::String
        "#{@protocol}::DataTypes::String.new(check: #{to_checks(checks)})"
      when Types::Binary
        # if type.struct
        #   "Structs::" + type.struct.name.as_class_name
        # else
        "#{@protocol}::DataTypes::Binary.new(check: #{to_checks(checks)})"
        # end
      when Types::NestedAttributes
        "#{@protocol}::DataTypes::NestedAttributes.new(#{type.attribute_set.name.as_class_name})"
      when Types::NestTypeValue
        "#{@protocol}::DataTypes::NestTypeValue.new(#{type.attribute_set.name.as_class_name}, #{type.type_values.length})"
      when Types::IndexedArray
        "#{@protocol}::DataTypes::IndexedArray.new(#{to_datatype(type.sub_type, nil)})"
      when Types::SubMessage
        "#{@protocol}::DataTypes::Binary.new(check: nil)"
      else
        raise "Unknown type: #{type.class}"
      end
    end

    private def to_checks(checks)
      return 'nil' if !checks || checks.empty?
      %Q{-> { #{checks.join('; ')} }}
    end
  end
end
