require 'rspec/core/rake_task'

NLSPEC_PATH = 'Documentation/netlink/specs'
NLSPEC_VERSION = File.read('NLSPEC_VERSION').chomp

RSpec::Core::RakeTask.new(:spec)

task default: :spec

directory 'generated'
directory 'generated/nl' => 'generated'
directory 'generated/nl/linux' => 'generated/nl'

specs = Dir['*.yaml', base: 'linux'].to_h do |spec|
  [
    spec,
    source: 'linux/' + spec,
    target: 'generated/nl/linux/' + spec.gsub(?-, ?_).sub(%r[\.yaml\z], '.rb'),
  ]
end

# For each of linux/%.yaml spec, generate generated/nl/linux/%.rb
specs.each do |spec, h|
  h => {source:, target:}
  task :generate => target
  task target => [source, 'generated/nl/linux', 'NLSPEC_VERSION', 'Rakefile'] do
    require 'ynl'
    File.open(source, 'r') do |src|
      comments = src.readlines.take_while {|l| !l.start_with?('---') }.grep(/\A\#/)

      File.open(target, 'w') do |out|
        out << comments.shift
        out << "#\n"
        out << "# This file is based on #{NLSPEC_PATH}/#{spec} from Linux v#{NLSPEC_VERSION}.\n"
        unless comments.empty?
          out << "#\n"
          out << "# Original YNL comment:\n"
          out << comments.join
        end
        out << "#--\n"
        out << Ynl::Generator::PRELUDE
        out << "module Nl; module Linux\n"
        Ynl::Family.generate(
          src.tap(&:rewind),
          out,
          default_resolver: '::Nl::Linux::DEFAULT_RESOLVER',
        )
        out << "end; end\n"
      end
    end
  end
end

task 'generated/nl/linux.rb' => [*specs.values.map { it[:target] }, 'Rakefile'] do |t|
  File.open(t.name, 'w') do |out|
    out << "require 'nl/linux/version'\n"
    out << "module Nl\n"
    out << "  module Linux\n"
    specs.values.map { it[:target] }.each do |f|
      cls = File.read(f)[/^class\s\K[^\s]+/]
      if cls
        out << "    autoload :#{cls}, #{f.sub('generated/', '').dump}\n"
      end
    end
    out << "  end\n"
    out << "end\n"
    out << "require 'nl/linux/nlctrl_resolver'\n"
  end
end
task :generate => 'generated/nl/linux.rb'

desc 'Generate RBS signatures from inline annotations'
task :rbs => :generate do
  sh 'rbs-inline', '--output=sig/generated', '--base=lib:generated', 'lib', 'generated'
end

task :build => :rbs

task :default => :generate
