name: Main

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
  schedule:
    - cron: '0 15 * * 5'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '4.0'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Generate
      run: bundle exec rake generate
    - name: Run tests
      run: bundle exec rake spec
