name: Main

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
  schedule:
    - cron: '0 15 * * 5'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '4.0'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Generate
      run: bundle exec rake generate
    - name: Run tests
      run: bundle exec rake spec

  build:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
    - uses: hanazuki/release-gems/build@e92c7bfeeee009a3de50fe3e02a72fb457f3baff

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    environment: rubygems.org
    runs-on: ubuntu-slim
    permissions:
      contents: write
      id-token: write
    steps:
    - uses: hanazuki/release-gems/publish@e92c7bfeeee009a3de50fe3e02a72fb457f3baff
